/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_example_feng_testjni4android_CallBack_NotifyEvent__H
#define J4A__com_example_feng_testjni4android_CallBack_NotifyEvent__H

#include "j4a/j4a_base.h"

void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postEvent(JNIEnv *env, jobject thiz, jint type, jstring msg);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postEvent__catchAll(JNIEnv *env, jobject thiz, jint type, jstring msg);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postEvent__withCString(JNIEnv *env, jobject thiz, jint type, const char *msg_cstr__);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postEvent__withCString__catchAll(JNIEnv *env, jobject thiz, jint type, const char *msg_cstr__);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postMsg(JNIEnv *env, jobject thiz, jint type, jstring msg);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postMsg__catchAll(JNIEnv *env, jobject thiz, jint type, jstring msg);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postMsg__withCString(JNIEnv *env, jobject thiz, jint type, const char *msg_cstr__);
void J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent__postMsg__withCString__catchAll(JNIEnv *env, jobject thiz, jint type, const char *msg_cstr__);
int J4A_loadClass__J4AC_com_example_feng_testjni4android_CallBack_NotifyEvent(JNIEnv *env);

#endif//J4A__com_example_feng_testjni4android_CallBack_NotifyEvent__H
